source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

# 使用正则表达式功能：
pod 'RegexKitLite-NoWarning', '1.1.0'

# 使用自适应键盘功能：
pod 'TPKeyboardAvoiding', '1.2.4'

# 使用功能：
pod 'BlocksKit', '2.2.5'

# 使用功能：
pod 'ReactiveCocoa', '2.3.1'

# 使用图片处理功能：
pod 'NYXImagesKit', '2.3'

# 使用功能：
pod 'UIImage+BlurredFrame', '0.0.4'

# 使用功能：
pod 'POP+MCAnimate', '2.0.1'

# 使用功能：
pod 'PPiAwesomeButton'

# 使用功能：
pod 'APParallaxHeader'

# 使用功能：
pod 'SDCAlertView', '2.5.2'

# 使用友盟设计分享功能：
pod 'UMengSocial', '4.2.3'

# 使用友盟分析功能：
pod 'UMengAnalytics', '3.5.10'

# 使用云后台LeanCloud功能：
pod 'AVOSCloud'

# 使用刷新控件功能：
pod 'MJRefresh'

# 使用引导页功能：
pod 'JazzHands', '2.0.0'

# 使用自适应适配功能：
pod 'Masonry', '0.5.3'

# 使用富文本功能：
pod 'TTTAttributedLabel', '1.10.1'

# 使用提示框功能：
pod 'MBProgressHUD', '0.9'

# 使用侧滑菜单功能：
pod 'SWTableViewCell', '~> 0.3.7'